-- Generated by Tools/BuildVerifiedData.lua from in-game verified data. Don't edit by hand.
local _, VA = ...

-- [key] = { name, mapID, x, y, lastSeen, { [itemID] = { price, cost, limited, pvp } }, seedID }
VA.shippedVendors = {
}

-- ["s" .. npcID] = { name, mapID, x, y, verifiedAt }
VA.shippedServices = {
}

VA.shippedItemNames = {
}
